"""empty message

Revision ID: 1dd4af39a4bb
Revises: 36213e0fd094
Create Date: 2017-02-09 11:47:36.273000

"""

# revision identifiers, used by Alembic.
revision = '1dd4af39a4bb'
down_revision = '36213e0fd094'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_esg_factor', sa.Column('data_provider_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'company_esg_factor', 'data_provider', ['data_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_esg_factor', type_='foreignkey')
    op.drop_column('company_esg_factor', 'data_provider_id')
    # ### end Alembic commands ###
