"""empty message

Revision ID: 2c91dcb26fab
Revises: 847ea34324ca
Create Date: 2017-02-08 13:42:30.729000

"""

# revision identifiers, used by Alembic.
revision = '2c91dcb26fab'
down_revision = '847ea34324ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('exchange', sa.String(length=20), nullable=True))
    op.add_column('company', sa.Column('ticker', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'ticker')
    op.drop_column('company', 'exchange')
    # ### end Alembic commands ###
