"""empty message

Revision ID: 36213e0fd094
Revises: 2c91dcb26fab
Create Date: 2017-02-08 14:20:47.100000

"""

# revision identifiers, used by Alembic.
revision = '36213e0fd094'
down_revision = '2c91dcb26fab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('custom_number_1', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('custom_number_2', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('custom_number_3', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('custom_number_4', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('custom_number_5', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('custom_text_1', sa.String(length=200), nullable=True))
    op.add_column('company', sa.Column('custom_text_2', sa.String(length=200), nullable=True))
    op.add_column('company', sa.Column('custom_text_3', sa.String(length=200), nullable=True))
    op.add_column('company', sa.Column('custom_text_4', sa.String(length=200), nullable=True))
    op.add_column('company', sa.Column('custom_text_5', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'custom_text_5')
    op.drop_column('company', 'custom_text_4')
    op.drop_column('company', 'custom_text_3')
    op.drop_column('company', 'custom_text_2')
    op.drop_column('company', 'custom_text_1')
    op.drop_column('company', 'custom_number_5')
    op.drop_column('company', 'custom_number_4')
    op.drop_column('company', 'custom_number_3')
    op.drop_column('company', 'custom_number_2')
    op.drop_column('company', 'custom_number_1')
    # ### end Alembic commands ###
