"""empty message

Revision ID: 533426e517c8
Revises: a6ece6a151e9
Create Date: 2017-01-25 15:42:23.788460

"""

# revision identifiers, used by Alembic.
revision = '533426e517c8'
down_revision = 'a6ece6a151e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_financial_series_quarterly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('geography_financial_series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_financial_series',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geography_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], name='geography_financial_series_geography_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='geography_financial_series_pkey')
    )
    op.drop_table('geography_financial_series_quarterly')
    # ### end Alembic commands ###
