"""empty message

Revision ID: 5bef031772b0
Revises: 74b2a0989d26
Create Date: 2017-02-16 14:02:30.144000

"""

# revision identifiers, used by Alembic.
revision = '5bef031772b0'
down_revision = '74b2a0989d26'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_esg_summary', sa.Column('e_score', sa.Float(), nullable=True))
    op.add_column('company_esg_summary', sa.Column('g_score', sa.Float(), nullable=True))
    op.add_column('company_esg_summary', sa.Column('rating', sa.String(length=5), nullable=True))
    op.add_column('company_esg_summary', sa.Column('s_score', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'company_esg_summary', 'esg_rating', ['rating'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_esg_summary', type_='foreignkey')
    op.drop_column('company_esg_summary', 's_score')
    op.drop_column('company_esg_summary', 'rating')
    op.drop_column('company_esg_summary', 'g_score')
    op.drop_column('company_esg_summary', 'e_score')
    # ### end Alembic commands ###
