"""empty message

Revision ID: 764465ae5355
Revises: c3fb9b469389
Create Date: 2017-02-17 15:56:39.804000

"""

# revision identifiers, used by Alembic.
revision = '764465ae5355'
down_revision = 'c3fb9b469389'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_asset',
    sa.Column('company_id', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_asset')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
