"""empty message

Revision ID: 847ea34324ca
Revises: 533426e517c8
Create Date: 2017-01-25 16:24:35.944631

"""

# revision identifiers, used by Alembic.
revision = '847ea34324ca'
down_revision = '533426e517c8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_geography_financial_series_quarterly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('geography_financial_series_quarterly')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_financial_series_quarterly',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geography_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['geography_id'], ['geography.id'], name='geography_financial_series_quarterly_geography_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='geography_financial_series_quarterly_pkey')
    )
    op.drop_table('company_geography_financial_series_quarterly')
    # ### end Alembic commands ###
