"""empty message

Revision ID: a79b5c20fcb3
Revises: None
Create Date: 2017-01-18 10:43:36.954000

"""

# revision identifiers, used by Alembic.
revision = 'a79b5c20fcb3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_simple_demo_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=64), nullable=False),
    sa.Column('setup_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esg_simple_demo_model')
    ### end Alembic commands ###
