"""empty message

Revision ID: b634c8e30bd7
Revises: 764465ae5355
Create Date: 2017-03-06 18:17:59.319000

"""

# revision identifiers, used by Alembic.
revision = 'b634c8e30bd7'
down_revision = '764465ae5355'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exposure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('asset_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'company', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'sector', ['sector_id'], ['id'])
    op.drop_constraint(u'company_asset_asset_id_fkey', 'company_asset', type_='foreignkey')
    # Column rename
    with op.batch_alter_table("company_asset") as batch_op:
        batch_op.alter_column('asset_id', new_column_name='asset_type_id')
    op.batch_alter_table(u'company_asset', op.alter_column('asset_id', 'asset_type_id'))
    op.create_foreign_key(None, 'company_asset', 'asset_type', ['asset_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'company_asset_asset_type_id_fkey', 'company_asset', type_='foreignkey')
    with op.batch_alter_table("company_asset") as batch_op:
        batch_op.alter_column('asset_type_id', new_column_name='asset_id')
    op.create_foreign_key(u'company_asset_asset_id_fkey', 'company_asset', 'asset_type', ['asset_id'], ['id'])
    op.drop_constraint(u'company_sector_id_fkey', 'company', type_='foreignkey')
    op.drop_column(u'company', 'sector_id')
    op.drop_table('exposure')
    op.drop_table('sector')
    # ### end Alembic commands ###
